<?php
CSF::createSection($prefix, array(
        'id'    => 'jubu',
        'title' => '局部美化',
        'icon'  => 'fa fa-object-group',
    ));
    CSF::createSection($prefix, array(
        'parent'      => 'jubu',
        'title'       => '右侧',
        'icon'        => 'fa fa-arrow-circle-right',
        'description' => '',
        'default'   =>true,
        'fields'      => array(
            array(
                'style'   => 'warning',
                'type'    => 'submessage',
            ), 
              array(
                'title'   => '纵向彩色滚动条',
                'label'   => '开启后可以美化网站右侧滚动条',
                'id'      => 'colorfulscrollbar',
                'default' => false,
                'type'    => 'switcher',
            ),
              array(
                'title'   => '右侧悬浮按钮栏',
                'label'   => '右侧悬浮按钮美化——欢迎光临',
                'id'      => 'youcexuanfu1',
                'default' => false,
                'type'    => 'switcher',
            ),
             array(
                'title'   => '右侧悬浮躲猫猫',
                'label'   => '开启后右侧可显示一只黑色猫猫，可以试试效果奥~',
                'id'      => 'youcexuanfu2',
                'default' => false,
                'type'    => 'switcher',
            ),
      ),));
      
       CSF::createSection($prefix, array(
        'parent'      => 'jubu',
        'title'       => '底部',
        'icon'        => 'fa fa-arrow-circle-down',
        'description' => '',
        'default'   =>true,
        'fields'      => array(
            array(
                'style'   => 'warning',
                'type'    => 'submessage',
            ),
            array(
                'title'   => '网站底部波浪',
                'label'   => '开启后可以在网站底部显示一个蓝色波浪',
                'id'      => 'bolang',
                'default' => false,
                'type'    => 'switcher',
            ),
            array(
                'title'   => '底部二维码滤镜一',
                'label'   => 'hue-rotate 色相旋转',
                'id'      => 'erweima1',
                'default' => false,
                'type'    => 'switcher',
            ),
            array(
                'title'   => '底部二维码滤镜二',
                'label'   => 'invert 反色',
                'id'      => 'erweima2',
                'default' => false,
                'type'    => 'switcher',
            ),
            array(
                'title'   => '底部二维码滤镜三',
                'label'   => 'drop-shadow 阴影',
                'id'      => 'erweima3',
                'default' => false,
                'type'    => 'switcher',
            ),
            array(
                'title'   => '底部收藏本站',
                'label'   => '开启后将在网站底部显示Ctrl+D收藏本站提示',
                'id'      => 'dixian',
                'default' => false,
                'type'    => 'switcher',
            ),
           array(
                'title'   => '网站底部广告',
                'label'   => '开启后可在网站底部显示广告',
                'id'      => 'advertisement',
                'default' => false,
                'type'    => 'switcher',
            ),
             array(
                'title'   => ' ',
                'desc'   => '请填写广告链接地址',
                'id'      => 'advertisement1',
                'default' => false,
                'type'    => 'text',
                'dependency' => array('advertisement', '!=', ''),
                'class'    =>'compact',
                
            ),
             array(
                'title'   => '右下角蒲公英',
                'label'   => '开启后网站底部将显示动态蒲公英特效',
                'id'      => 'plbj5',
                'default' => false,
                'type'    => 'switcher',
            ),
             array(
                'title'   => '底部导航栏',
                'label'   => '开启后可自定义网站底部导航',
                'id'      => 'plbj4',
                'default' => false,
                'type'    => 'switcher',
            ),
            array(
                'title'   => '文案&时间',
                'dependency' => array('plbj4', '!=', ''),
                'desc'    => '请填写左侧文案和时间',
                'id'      => 'bottomnav0',
                'default' => false,
                'type'    => 'text',
            ),
             array(
                'title'   => ' ',
                'desc'   => '请填写您的建站时间，如：2022-20-25',
                'id'      => 'timeauthor1',
                'default' => false,
                'type'    => 'text',
                'dependency' => array('plbj4', '!=', ''),
                'class'    =>'compact',
                
            ),
             array(
                'title'   => '导航一',
                'dependency' => array('plbj4', '!=', ''),
                'desc'    => '请填写导航文字',
                'id'      => 'bottomnav1',
                'default' => false,
                'type'    => 'text',
            ),
             array(
                'title'   => ' ',
                'dependency' => array('plbj4', '!=', ''),
                'desc'    => '请填写导航链接',
                'id'      => 'bottomhre1',
                'class'    =>'compact',
                'default' => false,
                'type'    => 'text',
            ),
             array(
                'title'   => '导航二',
                'dependency' => array('plbj4', '!=', ''),
                'id'      => 'bottomnav2',
                'desc'    => '请填写导航文字',
                'default' => false,
                'type'    => 'text',
            ),
             array(
                'title'   => ' ',
                'dependency' => array('plbj4', '!=', ''),
                'desc'    => '请填写导航链接',
                'class'    =>'compact',
                'id'      => 'bottomhre2',
                'default' => false,
                'type'    => 'text',
            ),
             array(
                'title'   => '导航三',
                'dependency' => array('plbj4', '!=', ''),
                'desc'    => '请填写导航文字',
                'id'      => 'bottomnav3',
                'default' => false,
                'type'    => 'text',
            ),
             array(
                'title'   => ' ',
                'dependency' => array('plbj4', '!=', ''),
                'desc'    => '请填写导航链接',
                'id'      => 'bottomhre3',
                'class'    =>'compact',
                'default' => false,
                'type'    => 'text',
            ),
             array(
                'title'   => '导航四',
                'dependency' => array('plbj4', '!=', ''),
                'desc'    => '请填写导航文字',
                'id'      => 'bottomnav4',
                'default' => false,
                'type'    => 'text',
            ),
             array(
                'title'   => ' ',
                'dependency' => array('plbj4', '!=', ''),
                'desc'    => '请填写导航链接',
                'class'    =>'compact',
                'id'      => 'bottomhre4',
                'default' => false,
                'type'    => 'text',
            ),
             array(
                'title'   => '导航五',
                'dependency' => array('plbj4', '!=', ''),
                'desc'    => '请填写导航文字',
                'id'      => 'bottomnav5',
                'default' => false,
                'type'    => 'text',
            ),
             array(
                'title'   => ' ',
                'dependency' => array('plbj4', '!=', ''),
                'desc'    => '请填写导航链接',
                'class'    =>'compact',
                'id'      => 'bottomhre5',
                'default' => false,
                'type'    => 'text',
            ),
      ),));
      
      CSF::createSection($prefix, array(
        'parent'      => 'jubu',
        'title'       => '左侧',
        'icon'        => 'fa fa-arrow-circle-left',
        'description' => '',
        'default'   =>true,
        'fields'      => array(
            array(
                'style'   => 'warning',
                'type'    => 'submessage',
            ), 
             array(
                'title'   => '左边联系站长QQ',
                'label'   => '开启后，电脑左侧边栏显示"联系站长”按钮',
                'desc'    => '注意：站长需要在前端个人中心填写个人QQ，否则无法实现跳转QQ<br>'.$shouquan_text,
                'id'      => 'contact_help_qq',
                'default' => false,
                'type'    => 'switcher',
            ),
             array(
                'title'   => '左边随便看看按钮',
                'label'   => '开启后，电脑左侧边栏显示"随便看看”按钮',
                'id'      => 'zibll_Add_ons_suibiankankan',
                'default' => false,
                'type'    => 'switcher',
            ),
      ),));
       CSF::createSection($prefix, array(
        'parent'      => 'jubu',
        'title'       => '顶部',
        'icon'        => 'fa fa-arrow-circle-up',
        'description' => '',
        'default'   =>true,
        'fields'      => array(
            array(
                'style'   => 'warning',
                'type'    => 'submessage',
            ), 
              array(
                'title'   => '元旦灯笼+梅花特效',
                'label'   => '启用后，网站右上角将呈现梅花和元旦灯笼特效',
                'id'      => 'chunjie',
                'default' => false,
                'type'    => 'switcher',
            ),
              array(
                'title'   => '顶部彩色进度条',
                'label'   => '启用后，网站顶部将显示一个彩色的进度条',
                'id'      => 'zibll_Add_ons_dingbu_jindutiao',
                'default' => false,
                'type'    => 'switcher',
            ),
            array(
                'title'   => '幻灯片指示器优化',
                'label'   => '启用后，幻灯片指示器将会圆角显示',
                'id'      => 'swiper',
                'default' => false,
                'type'    => 'switcher',
            ),
             array(
                'title'   => '自定义顶部切换标签',
                'label'   => '（你别走吖 ʕ ᵔᴥᵔ ʔ）（欢迎回来o( ❛ᴗ❛ o)',
                'id'      => 'dingbubiaoti',
                'default' => false,
                'type'    => 'switcher',
            ),
            array(
                'title'   => ' ',
                'desc'   => '当用户处于当前页面时的title文案)',
                'id'      => 'dingbubiaoti_mj1',
                'class'    =>'compact',
                'dependency' => array('dingbubiaoti', '!=', ''),
                'default' => '欢迎回来o( ❛ᴗ❛ ',
                'type'    => 'text',
            ),
            array(
                'title'   => ' ',
                'class'    =>'compact',
                'desc'   => '当用户离开当前页面时的title文案)',
                'id'      => 'dingbubiaoti_mj2',
                'dependency' => array('dingbubiaoti', '!=', ''),
                'default' => '你别走吖 ʕ ᵔᴥᵔ ʔ',
                'type'    => 'text',
            ),
             array(
                'title'   => '自定义顶部轮播标签',
                'id'      => 'dongtaibiaoti',
                'default' => false,
                'type'    => 'switcher',
                'label'    => '启用后，网站标签的title会显示一段轮播文字，注意，不能和“切换标签”混用',
            ),
             array(
                'title'   => ' ',
                'id'      => 'dongtaibiaoti1',
                'class'    =>'compact',
                'dependency' => array('dongtaibiaoti', '!=', ''),
                'default' => false,
                'type'    => 'text',
                'desc'    => '填写内容后，网站标签将会显示该内容的字幕，不填则不显示',
            ),
      ),));